[2023-07-26T11:50:22.331-0300] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: LH_ED_GABRIELLEMUNIZ.write_second_db manual__2023-07-26T14:23:45.992019+00:00 [queued]>
[2023-07-26T11:50:22.338-0300] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: LH_ED_GABRIELLEMUNIZ.write_second_db manual__2023-07-26T14:23:45.992019+00:00 [queued]>
[2023-07-26T11:50:22.339-0300] {taskinstance.py:1308} INFO - Starting attempt 4 of 7
[2023-07-26T11:50:22.359-0300] {taskinstance.py:1327} INFO - Executing <Task(PythonOperator): write_second_db> on 2023-07-26 14:23:45.992019+00:00
[2023-07-26T11:50:22.364-0300] {standard_task_runner.py:57} INFO - Started process 22859 to run task
[2023-07-26T11:50:22.367-0300] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'LH_ED_GABRIELLEMUNIZ', 'write_second_db', 'manual__2023-07-26T14:23:45.992019+00:00', '--job-id', '421', '--raw', '--subdir', 'DAGS_FOLDER/LH_ED_GABRIELLEMUNIZ.py', '--cfg-path', '/tmp/tmpgqki3w51']
[2023-07-26T11:50:22.368-0300] {standard_task_runner.py:85} INFO - Job 421: Subtask write_second_db
[2023-07-26T11:50:22.413-0300] {task_command.py:410} INFO - Running <TaskInstance: LH_ED_GABRIELLEMUNIZ.write_second_db manual__2023-07-26T14:23:45.992019+00:00 [running]> on host ubuntu
[2023-07-26T11:50:22.483-0300] {taskinstance.py:1545} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='gabi' AIRFLOW_CTX_DAG_ID='LH_ED_GABRIELLEMUNIZ' AIRFLOW_CTX_TASK_ID='write_second_db' AIRFLOW_CTX_EXECUTION_DATE='2023-07-26T14:23:45.992019+00:00' AIRFLOW_CTX_TRY_NUMBER='4' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-07-26T14:23:45.992019+00:00'
[2023-07-26T11:50:22.492-0300] {logging_mixin.py:150} WARNING - /home/gabi/Documentos/Gabi/Indicium/code-challenge-indicium/ind_env/lib/python3.10/site-packages/airflow/utils/context.py:313 AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
[2023-07-26T11:50:23.365-0300] {python.py:183} INFO - Done. Returned value was: None
[2023-07-26T11:50:23.371-0300] {taskinstance.py:1345} INFO - Marking task as SUCCESS. dag_id=LH_ED_GABRIELLEMUNIZ, task_id=write_second_db, execution_date=20230726T142345, start_date=20230726T145022, end_date=20230726T145023
[2023-07-26T11:50:23.422-0300] {local_task_job_runner.py:225} INFO - Task exited with return code 0
[2023-07-26T11:50:23.456-0300] {taskinstance.py:2653} INFO - 0 downstream tasks scheduled from follow-on schedule check
