[2023-07-26T11:47:11.156-0300] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: LH_ED_GABRIELLEMUNIZ.extract_write_local manual__2023-07-26T14:23:45.992019+00:00 [queued]>
[2023-07-26T11:47:11.162-0300] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: LH_ED_GABRIELLEMUNIZ.extract_write_local manual__2023-07-26T14:23:45.992019+00:00 [queued]>
[2023-07-26T11:47:11.163-0300] {taskinstance.py:1308} INFO - Starting attempt 7 of 9
[2023-07-26T11:47:11.181-0300] {taskinstance.py:1327} INFO - Executing <Task(PythonOperator): extract_write_local> on 2023-07-26 14:23:45.992019+00:00
[2023-07-26T11:47:11.186-0300] {standard_task_runner.py:57} INFO - Started process 22230 to run task
[2023-07-26T11:47:11.189-0300] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'LH_ED_GABRIELLEMUNIZ', 'extract_write_local', 'manual__2023-07-26T14:23:45.992019+00:00', '--job-id', '417', '--raw', '--subdir', 'DAGS_FOLDER/LH_ED_GABRIELLEMUNIZ.py', '--cfg-path', '/tmp/tmpdsb463qx']
[2023-07-26T11:47:11.190-0300] {standard_task_runner.py:85} INFO - Job 417: Subtask extract_write_local
[2023-07-26T11:47:11.239-0300] {task_command.py:410} INFO - Running <TaskInstance: LH_ED_GABRIELLEMUNIZ.extract_write_local manual__2023-07-26T14:23:45.992019+00:00 [running]> on host ubuntu
[2023-07-26T11:47:11.290-0300] {logging_mixin.py:150} WARNING - /home/gabi/Documentos/Gabi/Indicium/code-challenge-indicium/ind_env/lib/python3.10/site-packages/airflow/utils/context.py:205 AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
[2023-07-26T11:47:11.318-0300] {taskinstance.py:1545} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='gabi' AIRFLOW_CTX_DAG_ID='LH_ED_GABRIELLEMUNIZ' AIRFLOW_CTX_TASK_ID='extract_write_local' AIRFLOW_CTX_EXECUTION_DATE='2023-07-26T14:23:45.992019+00:00' AIRFLOW_CTX_TRY_NUMBER='7' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-07-26T14:23:45.992019+00:00'
[2023-07-26T11:47:11.321-0300] {taskinstance.py:1824} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/gabi/Documentos/Gabi/Indicium/code-challenge-indicium/ind_env/lib/python3.10/site-packages/airflow/operators/python.py", line 181, in execute
    return_value = self.execute_callable()
  File "/home/gabi/Documentos/Gabi/Indicium/code-challenge-indicium/ind_env/lib/python3.10/site-packages/airflow/operators/python.py", line 198, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/home/gabi/Documentos/Gabi/Indicium/code-challenge-indicium/dags/LH_ED_GABRIELLEMUNIZ.py", line 83, in extract_write_local
    date = datetime.strptime(execution_date, '%Y-%m-%d') if execution_date else kwargs['execution_date']
  File "/usr/lib/python3.10/_strptime.py", line 568, in _strptime_datetime
    tt, fraction, gmtoff_fraction = _strptime(data_string, format)
  File "/usr/lib/python3.10/_strptime.py", line 349, in _strptime
    raise ValueError("time data %r does not match format %r" %
ValueError: time data '                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 %2023-    %7-                %19' does not match format '%Y-%m-%d'
[2023-07-26T11:47:11.326-0300] {taskinstance.py:1345} INFO - Marking task as UP_FOR_RETRY. dag_id=LH_ED_GABRIELLEMUNIZ, task_id=extract_write_local, execution_date=20230726T142345, start_date=20230726T144711, end_date=20230726T144711
[2023-07-26T11:47:11.355-0300] {standard_task_runner.py:104} ERROR - Failed to execute job 417 for task extract_write_local (time data '                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 %2023-    %7-                %19' does not match format '%Y-%m-%d'; 22230)
[2023-07-26T11:47:11.401-0300] {local_task_job_runner.py:225} INFO - Task exited with return code 1
[2023-07-26T11:47:11.437-0300] {taskinstance.py:2653} INFO - 0 downstream tasks scheduled from follow-on schedule check
